### ISSUE TITLE
just a little sample in result_table.csv

### ISSUE THREAD

**Issue by Nina-SingleCell** [colomemaria/epiAneufinder#7] opened 2023-02-16 03:01 UTC
Whether I run the example data or my own data, the result I get is only a part of the cells, what caused this？
that is the code i use
```
epiAneufinder(input="./sample.tsv",outdir="./path/", blacklist="./hg38-blacklist.v2.bed", 
              windowSize=1e6, genome="BSgenome.Hsapiens.UCSC.hg38", exclude=c('chrX','chrY','chrM'), 
              reuse.existing=TRUE,title_karyo="Name",  ncores=24, minFrags=20000)
```

and this is the result i get
<img width="626" alt="image" src="https://user-images.githubusercontent.com/88649885/219256184-8155d9a4-6998-44a5-85a1-db650f75ee80.png">

and when i use myself data, the fragment has more than one thousand cells and the result tsv just has 30 cells. And i try to change the windowSize = 1e7 or windowSize = 1e8, but i got a error :
```
> epiAneufinder(input="try/fragments.tsv", outdir="try/",  blacklist="try/hg38-blacklist.v2.bed", 
              windowSize=1e7, genome="BSgenome.Hsapiens.UCSC.hg38", exclude=c('chrX','chrY','chrM'),
              reuse.existing=TRUE,title_karyo="1A", 
              ncores=24,minFrags=20000)

Subtracting Blacklist...
Adding Nucleotide Information...
1 of 21
2 of 21
3 of 21
4 of 21
5 of 21
6 of 21
7 of 21
8 of 21
9 of 21
10 of 21
11 of 21
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'sort': error in evaluating the argument 'x' in selecting a method for function 'sortSeqlevels': 'x' must be an array of at least two dimensions
```

**Comment by KatharinaSchmid** [comment] 2023-11-09 15:22
Hi Nina,
sorry for the very late answer and thanks for reporting the error. For your two questions:
1) The small number of recovered cells is probably caused by the strict cell filtering threshold. The default cell filtering threshold is at least 20,000 reads per cell (parameter minFrags). We would suggest that you test a more lenient threshold, e.g. minFrags=5,000. With this, you should hopefully recover far more cells.
2) We fixed the error that causes epiAneufinder to crash at very large bin sizes in our newest package version 1.0.2. It happens when the bin sizes are so large that they span an entire chromosome.

As we fixed the error now which you reported, I close this issue for now. If you still have problems with the new version of epiAneufinder, please let us know and reopen the issue.

**Closed by KatharinaSchmid** 2023-11-09 15:22 UTC
